version: '3'
services:
  node:
    image: node:18.16.0
    volumes:
      - ./web:/web
    working_dir: /web
    command: bash -c "npm install && npm run dev"
    links:
      - ruby
    depends_on:
      - ruby
    ports:
      - 8090:8090 # next.js
      - 6006:6006 # storybook
    environment:
      - PORT=8090
    networks:
      realworld_network:
        aliases:
          - node 
  ruby:
    image: ruby:2.7.8
    volumes:
      - ./api:/api
      - proxysql-sock:/var/lib/proxysql
    working_dir: /api
    command: bash -c "rm -rf tmp/*; bundle install && bin/rails db:create && bin/rails db:migrate && bin/rails db:seed && bundle exec rails s -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - PORT=3500
    links:
      - tidb
    depends_on:
      - tidb
      - proxysql
    networks:
      realworld_network:
        aliases:
          - ruby
    ports:
      - 3500:3500

  proxysql:
    build: ./docker/proxysql
    volumes:
      - proxysql-sock:/var/lib/proxysql
      - ./docker/proxysql/proxysql.cnf.template:/etc/proxysql.cnf.template
    ports:
      - "6033:6033" # mysql protocol
      - "6032:6032" # admin
    environment:
      - BACKEND_TIDB_HOST=tidb
      - BACKEND_TIDB_PORT=4000
      - BACKEND_TIDB_USER=root
      - BACKEND_TIDB_PASS=tidb1234
    networks:
      realworld_network:
        aliases:
          - proxysql
    links:
      - tidb
    depends_on:
      - tidb

  tidb:
    build:
      context: ./docker/tidb
      dockerfile: Dockerfile # v7.5.0
    command: /bin/sh -c "envsubst < /root/.tiup/initialize.sql.template > /root/.tiup/initialize.sql; exec /root/.tiup/bin/tiup playground v7.5.0 --host 0.0.0.0 --tag=devenv --db 1 --db.config /root/.tiup/tidb.toml --kv 1 --pd 1 --tiflash 0"
    ports:
      - "4000:4000"   # tidb(mysql protocol)
      - "10080:10080" # tidb(http protocol)
      - "2379:2379"   # pd/dashboard
      - "3000:3000"   # grafana
    networks:
      realworld_network:
        aliases:
          - tidb
    environment:
      - TIDB_ROOT_PASSWORD=tidb1234

volumes:
  proxysql-sock:
networks:
  realworld_network:
